[build]
  base = "frontend"
  command = "yarn build"
  publish = "frontend/build"

# Proxy de API (si tu backend ya está desplegado afuera)
[[redirects]]
  from = "/api/*"
  to = "https://aura.thrivesx.com/:splat"
  status = 200
  force = true