[build]
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_FLAGS = "--legacy-peer-deps"

# Proxy de /api/* (lo que ya tenías)
[[redirects]]
  from = "/api/*"
  to = "https://aura.thrivesx.com/:splat"
  status = 200
  force = true

# SPA fallback para React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200