[build]
  base = "frontend"
  command = "npm run build"
  publish = "build"
  
[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "https://aura.thrivesx.com/:splat"
  status = 200
  force = true

# Configuración de caché
[[caching]]
  directory = "/node_modules"
  paths = ["/node_modules/**", "/.cache/**"]